# Generated by Django 4.0.4 on 2022-04-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eidb', models.CharField(max_length=20)),
                ('enameb', models.CharField(max_length=100)),
                ('eAddressb', models.CharField(max_length=100)),
                ('eTremb', models.CharField(max_length=100)),
                ('eemailb', models.EmailField(max_length=254, verbose_name=100)),
                ('ePhone1b', models.CharField(max_length=25)),
                ('ePhone2b', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eidb', models.CharField(max_length=20)),
                ('epart_no', models.CharField(max_length=100)),
                ('egrade', models.CharField(max_length=100)),
                ('esize', models.CharField(max_length=100)),
                ('eselect', models.EmailField(max_length=254, verbose_name=100)),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Sub_contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('eAddress', models.CharField(max_length=100)),
                ('eTrem', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254, verbose_name=100)),
                ('ePhone1', models.CharField(max_length=25)),
                ('ePhone2', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'sub_contract',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eida', models.CharField(max_length=20)),
                ('enamea', models.CharField(max_length=100)),
                ('eAddressa', models.CharField(max_length=100)),
                ('eTrema', models.CharField(max_length=100)),
                ('eemaila', models.EmailField(max_length=254, verbose_name=100)),
                ('ePhone1a', models.CharField(max_length=25)),
                ('ePhone2a', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
    ]
