# Generated by Django 4.0.4 on 2022-10-11 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('BOMID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('BOM_Level', models.CharField(blank=True, default='', max_length=150)),
                ('product_name', models.CharField(blank=True, default='', max_length=150)),
                ('material_name', models.CharField(blank=True, default='', max_length=150)),
                ('source', models.CharField(default='', max_length=150)),
                ('UOM', models.TextField()),
                ('usage', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('remarks', models.CharField(default='', max_length=150)),
                ('amount', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'bom',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='', max_length=150)),
                ('address_ship', models.TextField()),
                ('address_sold', models.TextField()),
                ('address_bill', models.TextField()),
                ('term', models.TextField()),
                ('email', models.EmailField(max_length=150)),
                ('phone1', models.IntegerField()),
                ('phone2', models.IntegerField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(default='', max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('Female', 'Female'), ('secret', 'secret')], default='', max_length=150, null=True)),
                ('ICor_Passport_No', models.IntegerField()),
                ('moblie_contact', models.IntegerField()),
                ('email', models.EmailField(max_length=150)),
                ('date_birth', models.IntegerField()),
                ('date_join', models.IntegerField()),
                ('hour_rate_RM', models.IntegerField()),
                ('month_rate_RM', models.IntegerField()),
                ('position', models.CharField(default='', max_length=150)),
                ('level', models.IntegerField()),
                ('department', models.CharField(default='', max_length=150)),
                ('date_left', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ea0', models.CharField(default='', max_length=150)),
                ('ea1', models.CharField(default='', max_length=150)),
                ('ea2', models.CharField(default='', max_length=150)),
                ('ea3', models.CharField(default='', max_length=150)),
                ('ea4', models.CharField(default='', max_length=150)),
                ('ea5', models.CharField(default='', max_length=150)),
                ('ea6', models.CharField(default='', max_length=150)),
                ('ea7', models.CharField(default='', max_length=150)),
                ('ea8', models.CharField(default='', max_length=150)),
                ('ea9', models.CharField(default='', max_length=150)),
                ('ea10', models.CharField(default='', max_length=150)),
                ('ea11', models.CharField(default='', max_length=150)),
                ('ea12', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('MachineID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('machine_name', models.CharField(default='', max_length=150)),
                ('unit_price', models.IntegerField(verbose_name=150)),
            ],
            options={
                'db_table': 'machine',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('MaterialID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('material_name', models.CharField(default='', max_length=150)),
                ('measure_unit', models.CharField(default='', max_length=150)),
                ('tybe', models.CharField(default='', max_length=150)),
                ('Form', models.CharField(default='', max_length=150)),
                ('thickness', models.CharField(default='', max_length=150)),
                ('width', models.CharField(default='', max_length=150)),
                ('length', models.CharField(default='', max_length=150)),
                ('pltch', models.CharField(default='', max_length=150)),
                ('default_stock_locatiuon', models.CharField(default='', max_length=150)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Material_Supplier',
            fields=[
                ('MaterialSupplierID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('material_name', models.CharField(default='', max_length=150)),
                ('source', models.IntegerField()),
                ('UOM', models.IntegerField()),
                ('EOQ', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('term', models.IntegerField()),
                ('remarks', models.CharField(default='', max_length=150)),
                ('MaterialID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.material')),
            ],
            options={
                'db_table': 'material_supplier',
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('PackagingID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('packaging_name', models.CharField(default='', max_length=150)),
                ('packaging_unit', models.CharField(default='', max_length=150)),
                ('packaging_type', models.CharField(default='', max_length=150)),
                ('size', models.CharField(default='', max_length=150)),
                ('heigh', models.CharField(default='', max_length=150)),
                ('width', models.CharField(default='', max_length=150)),
                ('length', models.CharField(default='', max_length=150)),
                ('color', models.CharField(default='', max_length=150)),
                ('model', models.CharField(default='', max_length=150)),
                ('packaging_location', models.CharField(default='', max_length=150)),
                ('quantity', models.CharField(default='', max_length=150)),
                ('product_company', models.CharField(default='', max_length=150)),
                ('defaul_stock_location', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'packaging',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('ProcessID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('process_name', models.CharField(default='', max_length=150)),
                ('project_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('process_tooling', models.CharField(default='', max_length=150)),
                ('start_time', models.CharField(default='', max_length=150)),
                ('finish_time', models.CharField(default='', max_length=150)),
                ('duration', models.CharField(default='', max_length=150)),
                ('quanitiy', models.IntegerField(default='')),
                ('unit_price', models.IntegerField(default='')),
                ('cost', models.IntegerField(default='')),
                ('total', models.IntegerField(default='')),
            ],
            options={
                'db_table': 'process',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=150)),
                ('product_group', models.CharField(default='', max_length=150)),
                ('product_tooling', models.CharField(default='', max_length=150)),
                ('product_unit', models.CharField(default='', max_length=150)),
                ('BOM_Level', models.CharField(default='', max_length=150)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(verbose_name=150)),
                ('product_type', models.CharField(default='', max_length=150)),
                ('unit_price', models.IntegerField(verbose_name=150)),
                ('start_time', models.CharField(default='', max_length=150)),
                ('finish_time', models.CharField(default='', max_length=150)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pics')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Product_Quotation_Grand_Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re30', models.CharField(default='', max_length=150)),
                ('re31', models.CharField(default='', max_length=150)),
                ('re32', models.CharField(default='', max_length=150)),
                ('re33', models.CharField(default='', max_length=150)),
                ('re34', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'product_quotation_grand_total',
            },
        ),
        migrations.CreateModel(
            name='Product_Quotation_Material_Sub_Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re24', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('re25', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('re26', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('re27', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('re28', models.CharField(blank=True, default='', max_length=150, null=True)),
            ],
            options={
                'db_table': 'product_quotation_material_sub_total',
            },
        ),
        migrations.CreateModel(
            name='Product_Quotation_Process_Sub_Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re13', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='')),
                ('re14', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='')),
                ('re15', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='')),
                ('re16', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='')),
                ('re17', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='')),
            ],
            options={
                'db_table': 'product_quotation_process_sub_total',
            },
        ),
        migrations.CreateModel(
            name='Project_Sales_Item',
            fields=[
                ('ProjectSalesItemID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('project_name', models.CharField(default='', max_length=150)),
                ('customerpart_id', models.CharField(default='', max_length=150)),
                ('product_name', models.CharField(default='', max_length=150)),
                ('quantity', models.IntegerField(verbose_name=150)),
                ('unitprice', models.IntegerField(verbose_name=150)),
                ('project_date', models.IntegerField()),
                ('term', models.CharField(default='', max_length=150)),
                ('start_time', models.CharField(default='', max_length=150)),
                ('finish_time', models.CharField(default='', max_length=150)),
                ('DeliveryDatetime', models.CharField(default='', max_length=150)),
                ('CustomerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.customer')),
                ('ProductID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.product')),
            ],
            options={
                'db_table': 'project_sales_item',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('ResourceID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('reesource_name', models.CharField(default='', max_length=150)),
                ('remarks', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(default='', max_length=150)),
                ('supplier_type', models.CharField(default='', max_length=150)),
                ('address', models.TextField()),
                ('term', models.TextField()),
                ('email', models.CharField(default='', max_length=150)),
                ('phone1', models.IntegerField(verbose_name=150)),
                ('phone2', models.IntegerField(verbose_name=150)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Sales_Order',
            fields=[
                ('SalesOrderID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='', max_length=150)),
                ('term', models.TextField()),
                ('customer_po_id', models.CharField(default='', max_length=150)),
                ('description', models.CharField(default='', max_length=150)),
                ('quantity', models.CharField(default='', max_length=150)),
                ('unit_price', models.IntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='pics')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_time', models.CharField(default='', max_length=150)),
                ('finish_time', models.CharField(default='', max_length=150)),
                ('CustomerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.customer')),
                ('ProductID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.product')),
            ],
            options={
                'db_table': 'sales_order',
            },
        ),
        migrations.CreateModel(
            name='Require',
            fields=[
                ('RequireID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('product_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('material_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('product_usage', models.IntegerField(default='')),
                ('QTY_project', models.IntegerField(default='')),
                ('QTY_need', models.IntegerField(default='')),
                ('QTY_stock', models.IntegerField(default='')),
                ('QTY_purchase', models.IntegerField(default='')),
                ('remarks', models.CharField(default='', max_length=150)),
                ('quantity', models.CharField(default=0, max_length=150)),
                ('BOMID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.bom')),
                ('MaterialID', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.material')),
                ('ProductID', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.product')),
                ('ProjectSalesItemID', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.project_sales_item')),
            ],
            options={
                'db_table': 'require',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('PurchaseID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('purchase_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('require_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('material_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('quantity', models.IntegerField(default='')),
                ('unit_price', models.IntegerField(default='')),
                ('discount', models.IntegerField(default='')),
                ('total_MYR', models.IntegerField(default='')),
                ('remarks', models.CharField(default='', max_length=150)),
                ('deliver_date', models.CharField(default='', max_length=150)),
                ('MaterialID', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.material')),
                ('MaterialSupplierID', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.material_supplier')),
                ('RequireID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.require')),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
        migrations.AddField(
            model_name='project_sales_item',
            name='SalesOrderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.sales_order'),
        ),
        migrations.CreateModel(
            name='Product_Reject',
            fields=[
                ('RejectbatchID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=150)),
                ('type', models.TextField()),
                ('quantity', models.CharField(default='', max_length=150)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('MaterialID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.material')),
                ('ProductID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.product')),
            ],
            options={
                'db_table': 'product_reject',
            },
        ),
        migrations.CreateModel(
            name='Product_Quotation_Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('re8', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Process RM')),
                ('re9', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Job Start Time')),
                ('re10', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Job End Time')),
                ('re11', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Resources ID')),
                ('re12', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Person in Charge')),
                ('ProcessID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.process')),
            ],
            options={
                'db_table': 'product_quotation_process',
            },
        ),
        migrations.CreateModel(
            name='Product_Quotation_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('re19', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Material RM')),
                ('re20', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Stock On Hand')),
                ('re21', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Stock to Purchase')),
                ('re22', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Suppliers ID')),
                ('re23', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Person in Charge')),
                ('MaterialID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.material')),
            ],
            options={
                'db_table': 'product_quotation_material',
            },
        ),
        migrations.CreateModel(
            name='Product_Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re3', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Delivery Date')),
                ('re6', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Order Date')),
                ('CustomerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.customer')),
                ('ProductID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.product')),
                ('ProjectSalesItemID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.project_sales_item')),
                ('SalesOrderID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.sales_order')),
            ],
            options={
                'db_table': 'product_quotation',
            },
        ),
        migrations.CreateModel(
            name='Product_Material',
            fields=[
                ('ProductID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('usage', models.CharField(default='', max_length=150)),
                ('MaterialID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.material')),
            ],
            options={
                'db_table': 'product_material',
            },
        ),
        migrations.CreateModel(
            name='Product_Good',
            fields=[
                ('GoodbatchID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=150)),
                ('type', models.TextField()),
                ('quantity', models.CharField(default='', max_length=150)),
                ('term', models.CharField(default='', max_length=150)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('CustomerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.customer')),
                ('MaterialID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.material')),
                ('ProductID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.product')),
            ],
            options={
                'db_table': 'product_good',
            },
        ),
        migrations.AddField(
            model_name='process',
            name='ProductID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.product'),
        ),
        migrations.AddField(
            model_name='process',
            name='ProjectSalesItemID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.project_sales_item'),
        ),
        migrations.AddField(
            model_name='process',
            name='ResourceID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.resource'),
        ),
        migrations.AddField(
            model_name='material_supplier',
            name='SupplierID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.supplier'),
        ),
        migrations.CreateModel(
            name='Material_Stock',
            fields=[
                ('MaterialStockID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('material_name', models.CharField(default='', max_length=150)),
                ('material_location_id', models.CharField(default='', max_length=150)),
                ('shelf_id', models.CharField(default='', max_length=150)),
                ('quantity', models.IntegerField(verbose_name=150)),
                ('MaterialID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.material')),
            ],
            options={
                'db_table': 'material_stock',
            },
        ),
        migrations.CreateModel(
            name='Material_Receive',
            fields=[
                ('MaterialReceiveID', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(default='', max_length=150)),
                ('size', models.CharField(default='', max_length=150)),
                ('usage', models.CharField(default='', max_length=150)),
                ('quantity', models.CharField(default='', max_length=150)),
                ('remarks', models.CharField(default='', max_length=150)),
                ('MaterialID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.material')),
                ('SupplierID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.supplier')),
            ],
            options={
                'db_table': 'material_receive',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('DeliveryID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('sales_name', models.CharField(default='', max_length=150)),
                ('product_name', models.CharField(default='', max_length=150)),
                ('quantity', models.CharField(default='', max_length=150)),
                ('unitprice', models.CharField(default='', max_length=150)),
                ('term', models.TextField()),
                ('DeliveryDatetime', models.CharField(default='', max_length=150)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('CustomerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.customer')),
                ('ProductID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.product')),
                ('SalesOrderID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.sales_order')),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
        migrations.AddField(
            model_name='bom',
            name='MaterialID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.material'),
        ),
        migrations.AddField(
            model_name='bom',
            name='ProductID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERPSystem.product'),
        ),
    ]
