# Generated by Django 4.0.4 on 2022-10-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='sales_order',
            name='photo',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
