# Generated by Django 4.0.4 on 2022-06-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERPSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packaging',
            old_name='packaging_heigh',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='packaging',
            old_name='packaging_color',
            new_name='heigh',
        ),
        migrations.RenameField(
            model_name='packaging',
            old_name='packaging_length',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='packaging',
            old_name='packaging_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='packaging',
            old_name='packaging_width',
            new_name='width',
        ),
    ]
