# Generated by Django 4.0.4 on 2022-10-12 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ERPSystem', '0002_alter_product_photo_alter_sales_order_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Sales_Records',
            fields=[
                ('ProductSalesRecordsID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('SalesOrderID', models.CharField(default='', max_length=150)),
                ('CustomerID', models.CharField(default='', max_length=150)),
                ('customer_name', models.CharField(default='', max_length=150)),
                ('term', models.TextField()),
                ('customer_po_id', models.CharField(default='', max_length=150)),
                ('ProductID', models.CharField(default='', max_length=150)),
                ('description', models.CharField(default='', max_length=150)),
                ('quantity', models.CharField(default='', max_length=150)),
                ('unit_price', models.IntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('photo', models.ImageField(default='', upload_to='pics')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_time', models.CharField(default='', max_length=150)),
                ('finish_time', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'product_sales_records',
            },
        ),
    ]
